services:
  - type: web
    name: WISE
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npx prisma generate && cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"