services:
  - type: web
    name: WISE
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npx puppeteer browsers install chrome && npx prisma generate && cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: VERIFY_BASE_URL
        value: https://parsuwise.onrender.com/verify
      - key: API_BASE_URL
        value: https://parsuwise.onrender.com